#!/bin/bash

CAPS='application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)MP2T-ES, payload=(int)33'
#CAPS='video/mpegts, systemstream=(boolean)true, packetsize=(int)188'

listenport=6050
serverport=6060
server=81.7.134.69

function on_error {
	echo "Error. Usage : $0 udp|tcp"
	exit 1
}

if [ $# != 1 ] ; then on_error
fi

if [ $1 != udp -a $1 != tcp ] ; then on_error
fi

gstlaunch=`which gst-launch-1.0`
if [ X$gstlaunch != X ] ; then
  VIDEOCONVERT=videoconvert
  VIDEO=video/x-raw
  AUDIO=audio/x-raw
  vfid=string
  afid="format=(string)S16LE, "
else
  gstlaunch=`which gst-launch-0.10`
  if [ X$gstlaunch != X ] ; then
    VIDEOCONVERT=ffmpegcolorspace
    VIDEO=video/x-raw-rgb
    AUDIO=audio/x-raw-int
    vfid=fourcc
    afid=""
  else
    echo "Could not find gst-launch-1.0 or gst-launch-0.10. Stopping"
    exit
  fi
fi


while true ; do
	if [ $1 = udp ] ; then
		#--gst-debug=rtpmp2tdepay:5
		echo Listen on UDP port 6050 and make available on TCP port 6060
		$gstlaunch -v --gst-debug=2  udpsrc port=$listenport buffer-size=1000000 caps="$CAPS"	! \
			queue					! \
			rtpmp2tdepay				! \
			mpegtsparse ! \
			tcpserversink port=$serverport sync-method=2
			#tcpserversink port=$serverport
	else
		echo Listen on TCP port 6050 and make available on TCP port 6060
		$gstlaunch -v tcpserversrc port=$listenport host=$server	! \
			mpegtsparse				! \
			queue					! \
			tcpserversink port=$serverport sync-method=2
	fi
	sleep 5
done
